# Generated by Django 6.0 on 2025-12-25 18:35

from django.db import migrations


def migrate_imagenes(apps, schema_editor):
    Producto = apps.get_model('tienda', 'Producto')
    ProductImage = apps.get_model('tienda', 'ProductImage')
    for producto in Producto.objects.all():
        if hasattr(producto, 'imagen') and producto.imagen:
            ProductImage.objects.create(producto=producto, imagen=producto.imagen)


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_imagenes),
    ]
