# Generated by Django 6.0 on 2025-12-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20251225_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='is_oferta',
            field=models.BooleanField(default=False),
        ),
    ]
